[2023-08-02 05:56:04,008] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: s3_to_postgres.load_weather_data scheduled__2023-08-01T05:56:00.389552+00:00 [queued]>
[2023-08-02 05:56:04,019] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: s3_to_postgres.load_weather_data scheduled__2023-08-01T05:56:00.389552+00:00 [queued]>
[2023-08-02 05:56:04,019] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-02 05:56:04,019] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-08-02 05:56:04,019] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-02 05:56:04,389] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): load_weather_data> on 2023-08-01 05:56:00.389552+00:00
[2023-08-02 05:56:04,395] {standard_task_runner.py:52} INFO - Started process 202 to run task
[2023-08-02 05:56:04,398] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 's3_to_postgres', 'load_weather_data', 'scheduled__2023-08-01T05:56:00.389552+00:00', '--job-id', '234', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp8l_sghhg', '--error-file', '/tmp/tmpgpo4p61f']
[2023-08-02 05:56:04,399] {standard_task_runner.py:80} INFO - Job 234: Subtask load_weather_data
[2023-08-02 05:56:04,476] {task_command.py:370} INFO - Running <TaskInstance: s3_to_postgres.load_weather_data scheduled__2023-08-01T05:56:00.389552+00:00 [running]> on host 656341a29da6
[2023-08-02 05:56:04,579] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=s3_to_postgres
AIRFLOW_CTX_TASK_ID=load_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-01T05:56:00.389552+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-01T05:56:00.389552+00:00
[2023-08-02 05:56:04,580] {logging_mixin.py:115} INFO - 
 heeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeyy
[2023-08-02 05:56:05,250] {logging_mixin.py:115} INFO - 
✅ DataFrame created ! ✅
[2023-08-02 05:56:14,194] {gbq.py:606} INFO - 13 out of 13 rows loaded.
[2023-08-02 05:56:14,195] {logging_mixin.py:115} INFO - 
✅ Table 2023-08-01 upload on BigQuery! ✅
[2023-08-02 05:56:14,195] {python.py:173} INFO - Done. Returned value was: None
[2023-08-02 05:56:14,257] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=s3_to_postgres, task_id=load_weather_data, execution_date=20230801T055600, start_date=20230802T055604, end_date=20230802T055614
[2023-08-02 05:56:14,839] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-02 05:56:14,884] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
