[2023-08-01 23:01:19,773] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: s3_to_BigQuery.stations_data_to_BQ manual__2023-08-01T23:01:15.953964+00:00 [queued]>
[2023-08-01 23:01:19,783] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: s3_to_BigQuery.stations_data_to_BQ manual__2023-08-01T23:01:15.953964+00:00 [queued]>
[2023-08-01 23:01:19,784] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-01 23:01:19,784] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-08-01 23:01:19,784] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-01 23:01:19,840] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): stations_data_to_BQ> on 2023-08-01 23:01:15.953964+00:00
[2023-08-01 23:01:19,855] {standard_task_runner.py:52} INFO - Started process 95 to run task
[2023-08-01 23:01:19,864] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 's3_to_BigQuery', 'stations_data_to_BQ', 'manual__2023-08-01T23:01:15.953964+00:00', '--job-id', '213', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpxda8lz4f', '--error-file', '/tmp/tmp1xqj76ph']
[2023-08-01 23:01:19,866] {standard_task_runner.py:80} INFO - Job 213: Subtask stations_data_to_BQ
[2023-08-01 23:01:20,098] {task_command.py:370} INFO - Running <TaskInstance: s3_to_BigQuery.stations_data_to_BQ manual__2023-08-01T23:01:15.953964+00:00 [running]> on host 55717dddfd31
[2023-08-01 23:01:20,484] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=s3_to_BigQuery
AIRFLOW_CTX_TASK_ID=stations_data_to_BQ
AIRFLOW_CTX_EXECUTION_DATE=2023-08-01T23:01:15.953964+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-01T23:01:15.953964+00:00
[2023-08-01 23:01:20,485] {logging_mixin.py:115} INFO - 
 heeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeyy
[2023-08-01 23:01:21,273] {logging_mixin.py:115} INFO - 
✅ DataFrame created ! ✅
[2023-08-01 23:01:21,273] {logging_mixin.py:115} INFO - Error: [Errno 2] No such file or directory: '/opt/***/pluginslime-project-key.json'
[2023-08-01 23:01:21,274] {python.py:173} INFO - Done. Returned value was: None
[2023-08-01 23:01:21,284] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=s3_to_BigQuery, task_id=stations_data_to_BQ, execution_date=20230801T230115, start_date=20230801T230119, end_date=20230801T230121
[2023-08-01 23:01:21,360] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-01 23:01:21,421] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
