[2023-08-02 09:17:19,036] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: S3_to_BigQuery.load_stations_data manual__2023-08-02T09:17:16.461598+00:00 [queued]>
[2023-08-02 09:17:19,044] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: S3_to_BigQuery.load_stations_data manual__2023-08-02T09:17:16.461598+00:00 [queued]>
[2023-08-02 09:17:19,044] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-02 09:17:19,044] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-08-02 09:17:19,044] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-02 09:17:19,067] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): load_stations_data> on 2023-08-02 09:17:16.461598+00:00
[2023-08-02 09:17:19,071] {standard_task_runner.py:52} INFO - Started process 9600 to run task
[2023-08-02 09:17:19,074] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'S3_to_BigQuery', 'load_stations_data', 'manual__2023-08-02T09:17:16.461598+00:00', '--job-id', '301', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp5kmepesq', '--error-file', '/tmp/tmpmc_kayiv']
[2023-08-02 09:17:19,074] {standard_task_runner.py:80} INFO - Job 301: Subtask load_stations_data
[2023-08-02 09:17:19,128] {task_command.py:370} INFO - Running <TaskInstance: S3_to_BigQuery.load_stations_data manual__2023-08-02T09:17:16.461598+00:00 [running]> on host 656341a29da6
[2023-08-02 09:17:19,221] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=S3_to_BigQuery
AIRFLOW_CTX_TASK_ID=load_stations_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-02T09:17:16.461598+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-02T09:17:16.461598+00:00
[2023-08-02 09:17:21,715] {logging_mixin.py:115} INFO - 
DataFrame push into xcom.
[2023-08-02 09:17:22,526] {logging_mixin.py:115} INFO - 
DATAFRAME SHAPE : (16003, 8)
[2023-08-02 09:17:22,526] {logging_mixin.py:115} INFO - 
✅ DataFrame created ! ✅
[2023-08-02 09:17:22,551] {logging_mixin.py:115} INFO - Error: name 'key' is not defined
[2023-08-02 09:17:22,559] {python.py:173} INFO - Done. Returned value was: None
[2023-08-02 09:17:22,573] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=S3_to_BigQuery, task_id=load_stations_data, execution_date=20230802T091716, start_date=20230802T091719, end_date=20230802T091722
[2023-08-02 09:17:22,618] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-02 09:17:22,664] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
