[2023-08-01 23:05:51,337] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: s3_to_BigQuery.stations_data_to_BQ manual__2023-08-01T23:05:46.175001+00:00 [queued]>
[2023-08-01 23:05:51,348] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: s3_to_BigQuery.stations_data_to_BQ manual__2023-08-01T23:05:46.175001+00:00 [queued]>
[2023-08-01 23:05:51,348] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-01 23:05:51,348] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-08-01 23:05:51,348] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-01 23:05:51,573] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): stations_data_to_BQ> on 2023-08-01 23:05:46.175001+00:00
[2023-08-01 23:05:51,587] {standard_task_runner.py:52} INFO - Started process 86 to run task
[2023-08-01 23:05:51,594] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 's3_to_BigQuery', 'stations_data_to_BQ', 'manual__2023-08-01T23:05:46.175001+00:00', '--job-id', '219', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpuzqm19qd', '--error-file', '/tmp/tmpdnceaidp']
[2023-08-01 23:05:51,597] {standard_task_runner.py:80} INFO - Job 219: Subtask stations_data_to_BQ
[2023-08-01 23:05:51,740] {task_command.py:370} INFO - Running <TaskInstance: s3_to_BigQuery.stations_data_to_BQ manual__2023-08-01T23:05:46.175001+00:00 [running]> on host e73b972b08ee
[2023-08-01 23:05:52,039] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=s3_to_BigQuery
AIRFLOW_CTX_TASK_ID=stations_data_to_BQ
AIRFLOW_CTX_EXECUTION_DATE=2023-08-01T23:05:46.175001+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-01T23:05:46.175001+00:00
[2023-08-01 23:05:52,040] {logging_mixin.py:115} INFO - 
 heeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeyy
[2023-08-01 23:05:52,964] {logging_mixin.py:115} INFO - 
✅ DataFrame created ! ✅
[2023-08-01 23:05:52,965] {logging_mixin.py:115} INFO - Error: [Errno 2] No such file or directory: '/opt/***/pluginslime-project-key.json'
[2023-08-01 23:05:52,969] {python.py:173} INFO - Done. Returned value was: None
[2023-08-01 23:05:53,075] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=s3_to_BigQuery, task_id=stations_data_to_BQ, execution_date=20230801T230546, start_date=20230801T230551, end_date=20230801T230553
[2023-08-01 23:05:53,210] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-01 23:05:53,316] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
