[2023-08-01 22:52:21,591] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: s3_to_BigQuery.weather_data_to_BQ manual__2023-08-01T22:52:17.316354+00:00 [queued]>
[2023-08-01 22:52:21,603] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: s3_to_BigQuery.weather_data_to_BQ manual__2023-08-01T22:52:17.316354+00:00 [queued]>
[2023-08-01 22:52:21,604] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-01 22:52:21,604] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-08-01 22:52:21,604] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-01 22:52:21,631] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): weather_data_to_BQ> on 2023-08-01 22:52:17.316354+00:00
[2023-08-01 22:52:21,636] {standard_task_runner.py:52} INFO - Started process 88 to run task
[2023-08-01 22:52:21,639] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 's3_to_BigQuery', 'weather_data_to_BQ', 'manual__2023-08-01T22:52:17.316354+00:00', '--job-id', '203', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmprn1bt3it', '--error-file', '/tmp/tmpkg7d3xx3']
[2023-08-01 22:52:21,640] {standard_task_runner.py:80} INFO - Job 203: Subtask weather_data_to_BQ
[2023-08-01 22:52:21,701] {task_command.py:370} INFO - Running <TaskInstance: s3_to_BigQuery.weather_data_to_BQ manual__2023-08-01T22:52:17.316354+00:00 [running]> on host 11cc9cd02b17
[2023-08-01 22:52:21,817] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=s3_to_BigQuery
AIRFLOW_CTX_TASK_ID=weather_data_to_BQ
AIRFLOW_CTX_EXECUTION_DATE=2023-08-01T22:52:17.316354+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-01T22:52:17.316354+00:00
[2023-08-01 22:52:21,827] {logging_mixin.py:115} INFO - 
 heeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeyy
[2023-08-01 22:52:22,438] {logging_mixin.py:115} INFO - 
✅ DataFrame created ! ✅
[2023-08-01 22:52:22,439] {logging_mixin.py:115} INFO - Error: [Errno 2] No such file or directory: '/opt/***/pluginslime-project-key.json'
[2023-08-01 22:52:22,440] {python.py:173} INFO - Done. Returned value was: None
[2023-08-01 22:52:22,501] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=s3_to_BigQuery, task_id=weather_data_to_BQ, execution_date=20230801T225217, start_date=20230801T225221, end_date=20230801T225222
[2023-08-01 22:52:22,614] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-01 22:52:22,671] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
