[2023-08-02 09:02:12,912] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: S3_to_BigQuery.load_stations_data manual__2023-08-02T09:02:10.868755+00:00 [queued]>
[2023-08-02 09:02:12,920] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: S3_to_BigQuery.load_stations_data manual__2023-08-02T09:02:10.868755+00:00 [queued]>
[2023-08-02 09:02:12,920] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-02 09:02:12,920] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-08-02 09:02:12,920] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-02 09:02:12,947] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): load_stations_data> on 2023-08-02 09:02:10.868755+00:00
[2023-08-02 09:02:12,952] {standard_task_runner.py:52} INFO - Started process 8897 to run task
[2023-08-02 09:02:12,954] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'S3_to_BigQuery', 'load_stations_data', 'manual__2023-08-02T09:02:10.868755+00:00', '--job-id', '295', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpj6v363vq', '--error-file', '/tmp/tmpi43_e6j6']
[2023-08-02 09:02:12,955] {standard_task_runner.py:80} INFO - Job 295: Subtask load_stations_data
[2023-08-02 09:02:13,013] {task_command.py:370} INFO - Running <TaskInstance: S3_to_BigQuery.load_stations_data manual__2023-08-02T09:02:10.868755+00:00 [running]> on host 656341a29da6
[2023-08-02 09:02:13,106] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=S3_to_BigQuery
AIRFLOW_CTX_TASK_ID=load_stations_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-02T09:02:10.868755+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-02T09:02:10.868755+00:00
[2023-08-02 09:02:15,037] {logging_mixin.py:115} INFO - 
DataFrame push into xcom.
[2023-08-02 09:02:15,911] {logging_mixin.py:115} INFO - 
DATAFRAME SHAPE : (16003, 8)
[2023-08-02 09:02:15,911] {logging_mixin.py:115} INFO - 
✅ DataFrame created ! ✅
[2023-08-02 09:02:15,931] {logging_mixin.py:115} INFO - 
KEY XCOM : lime_stations_topic_json
[2023-08-02 09:02:16,527] {logging_mixin.py:115} INFO - 
✅ Push to xcom ! ✅
[2023-08-02 09:02:16,965] {logging_mixin.py:115} INFO - Error: Could not create the table because it already exists. Change the if_exists parameter to 'append' or 'replace' data.
[2023-08-02 09:02:16,972] {python.py:173} INFO - Done. Returned value was: None
[2023-08-02 09:02:16,982] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=S3_to_BigQuery, task_id=load_stations_data, execution_date=20230802T090210, start_date=20230802T090212, end_date=20230802T090216
[2023-08-02 09:02:17,058] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-02 09:02:17,111] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
