[2023-08-02 09:30:47,959] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: S3_to_BigQuery.load_weather_data manual__2023-08-02T09:30:45.813128+00:00 [queued]>
[2023-08-02 09:30:47,974] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: S3_to_BigQuery.load_weather_data manual__2023-08-02T09:30:45.813128+00:00 [queued]>
[2023-08-02 09:30:47,974] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-02 09:30:47,974] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-08-02 09:30:47,974] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-02 09:30:47,997] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): load_weather_data> on 2023-08-02 09:30:45.813128+00:00
[2023-08-02 09:30:48,001] {standard_task_runner.py:52} INFO - Started process 10244 to run task
[2023-08-02 09:30:48,004] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'S3_to_BigQuery', 'load_weather_data', 'manual__2023-08-02T09:30:45.813128+00:00', '--job-id', '312', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpwd7oqg2l', '--error-file', '/tmp/tmpe_3i6ms1']
[2023-08-02 09:30:48,005] {standard_task_runner.py:80} INFO - Job 312: Subtask load_weather_data
[2023-08-02 09:30:48,059] {task_command.py:370} INFO - Running <TaskInstance: S3_to_BigQuery.load_weather_data manual__2023-08-02T09:30:45.813128+00:00 [running]> on host 656341a29da6
[2023-08-02 09:30:48,947] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=S3_to_BigQuery
AIRFLOW_CTX_TASK_ID=load_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-02T09:30:45.813128+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-02T09:30:45.813128+00:00
[2023-08-02 09:30:49,476] {logging_mixin.py:115} INFO - 
DataFrame push into xcom.
[2023-08-02 09:30:49,481] {logging_mixin.py:115} INFO - 
DATAFRAME SHAPE : (13, 11)
[2023-08-02 09:30:49,481] {logging_mixin.py:115} INFO - 
✅ DataFrame created ! ✅
[2023-08-02 09:30:49,514] {logging_mixin.py:115} INFO - 
✅ Push to xcom ! ✅
[2023-08-02 09:30:49,516] {python.py:173} INFO - Done. Returned value was: None
[2023-08-02 09:30:49,530] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=S3_to_BigQuery, task_id=load_weather_data, execution_date=20230802T093045, start_date=20230802T093047, end_date=20230802T093049
[2023-08-02 09:30:49,581] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-02 09:30:49,646] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
