[2023-08-03 03:22:05,789] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: S3_to_BigQuery.load_weather_data manual__2023-08-03T03:22:03.288396+00:00 [queued]>
[2023-08-03 03:22:05,798] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: S3_to_BigQuery.load_weather_data manual__2023-08-03T03:22:03.288396+00:00 [queued]>
[2023-08-03 03:22:05,798] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-03 03:22:05,798] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-08-03 03:22:05,798] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-03 03:22:05,837] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): load_weather_data> on 2023-08-03 03:22:03.288396+00:00
[2023-08-03 03:22:05,841] {standard_task_runner.py:52} INFO - Started process 104 to run task
[2023-08-03 03:22:05,845] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'S3_to_BigQuery', 'load_weather_data', 'manual__2023-08-03T03:22:03.288396+00:00', '--job-id', '445', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpvl8duqgm', '--error-file', '/tmp/tmprcec8gdl']
[2023-08-03 03:22:05,846] {standard_task_runner.py:80} INFO - Job 445: Subtask load_weather_data
[2023-08-03 03:22:06,101] {task_command.py:370} INFO - Running <TaskInstance: S3_to_BigQuery.load_weather_data manual__2023-08-03T03:22:03.288396+00:00 [running]> on host 6c95ca7a45b2
[2023-08-03 03:22:08,675] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=S3_to_BigQuery
AIRFLOW_CTX_TASK_ID=load_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-03T03:22:03.288396+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-03T03:22:03.288396+00:00
[2023-08-03 03:22:11,068] {logging_mixin.py:115} INFO - 
✅ Push to xcom ! ✅
[2023-08-03 03:22:11,070] {python.py:173} INFO - Done. Returned value was: None
[2023-08-03 03:22:11,082] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=S3_to_BigQuery, task_id=load_weather_data, execution_date=20230803T032203, start_date=20230803T032205, end_date=20230803T032211
[2023-08-03 03:22:11,157] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-03 03:22:11,210] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
