[2023-08-02 13:53:07,212] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: S3_to_BigQuery.upload_weather_data manual__2023-08-02T13:52:59.429748+00:00 [queued]>
[2023-08-02 13:53:07,221] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: S3_to_BigQuery.upload_weather_data manual__2023-08-02T13:52:59.429748+00:00 [queued]>
[2023-08-02 13:53:07,221] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-02 13:53:07,221] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-08-02 13:53:07,221] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-02 13:53:07,250] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): upload_weather_data> on 2023-08-02 13:52:59.429748+00:00
[2023-08-02 13:53:07,255] {standard_task_runner.py:52} INFO - Started process 2785 to run task
[2023-08-02 13:53:07,258] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'S3_to_BigQuery', 'upload_weather_data', 'manual__2023-08-02T13:52:59.429748+00:00', '--job-id', '392', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpa3v11wrf', '--error-file', '/tmp/tmpv31kmj6n']
[2023-08-02 13:53:07,259] {standard_task_runner.py:80} INFO - Job 392: Subtask upload_weather_data
[2023-08-02 13:53:07,322] {task_command.py:370} INFO - Running <TaskInstance: S3_to_BigQuery.upload_weather_data manual__2023-08-02T13:52:59.429748+00:00 [running]> on host f57ce474b9bb
[2023-08-02 13:53:07,445] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=S3_to_BigQuery
AIRFLOW_CTX_TASK_ID=upload_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-02T13:52:59.429748+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-02T13:52:59.429748+00:00
[2023-08-02 13:53:07,460] {logging_mixin.py:115} INFO - Error: the JSON object must be str, bytes or bytearray, not NoneType
[2023-08-02 13:53:07,460] {python.py:173} INFO - Done. Returned value was: None
[2023-08-02 13:53:07,500] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=S3_to_BigQuery, task_id=upload_weather_data, execution_date=20230802T135259, start_date=20230802T135307, end_date=20230802T135307
[2023-08-02 13:53:07,590] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-02 13:53:07,650] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
